name: Release
on: 
  push:
    branches:
      -main
jobs:
  name: release
  runs-on: ubuntu
  steps:
    - name: checkout
      uses: actions/checkout@v3   
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.0.0
    - name: Install dependencies
      run: npm ci
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
